server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: ItemMaster
          uri: http://localhost:8081
          predicates:
            - Path=/items/**, 
        - id: Process
          uri: http://localhost:8082
          predicates:
            - Path=/processes/**, 
        - id: Material
          uri: http://localhost:8083
          predicates:
            - Path=/materials/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ItemMaster
          uri: http://itemMaster:8080
          predicates:
            - Path=/items/**, 
        - id: Process
          uri: http://process:8080
          predicates:
            - Path=/processes/**, 
        - id: Material
          uri: http://material:8080
          predicates:
            - Path=/materials/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
