---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ItemMaster
  labels:
    app: ItemMaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ItemMaster
  template:
    metadata:
      labels:
        app: ItemMaster
    spec:
      containers:
        - name: ItemMaster
          image: username/ItemMaster:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Process
  labels:
    app: Process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Process
  template:
    metadata:
      labels:
        app: Process
    spec:
      containers:
        - name: Process
          image: username/Process:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Material
  labels:
    app: Material
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Material
  template:
    metadata:
      labels:
        app: Material
    spec:
      containers:
        - name: Material
          image: username/Material:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ItemMaster
  labels:
    app: ItemMaster
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ItemMaster


---


apiVersion: v1
kind: Service
metadata:
  name: Process
  labels:
    app: Process
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Process


---


apiVersion: v1
kind: Service
metadata:
  name: Material
  labels:
    app: Material
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Material

